---
title: "[]{#_ulsrub3fv3lf .anchor}DFT / FFT / STFT"
---

# Discrete Fourier Transform (DFT)

- The [Fourier transform](?tab=t.lu5907fvi1t4#heading=h.bzwks5sw9lxj) coefficients are

  - $F(\xi) = \int_{- \infty}^{\infty}f(t)e^{- i2\pi\xi t}dt$

- However, continuous signals can\'t be handled on a computer.

- The Discrete Time Fourier Transform (DTFT) discretizes the signal (i.e. discretizes time, samples the signal).

  - $F(e^{i\omega}) = \sum_{n = - \infty}^{\infty}f\lbrack n\rbrack e^{- i\omega n}$

  - $\xi \rightarrow \omega = 2\pi f$

  - $F(\omega)$ vs $F(e^{i\omega})$

- With the DTFT, the time is now discrete but

  - There is an infinite sum (not possible in practice).

  - Frequency is still continuous.

- The Discrete Fourier Transform (DFT) solves these issues by

  - Truncating time, i.e. looking at a finite time window of N samples.

  - Discretizing frequency, i.e. calculating frequency bins at specific intervals.

- The DFT is computable but it is very slow. Its complexity is $0(N^{2})$.

# Fast Fourier Transform (FFT)

- The Fast Fourier Transform (FFT) is an algorithm that implements the DFT in an efficient way.

- It uses a divide and conquer strategy.

- It reduces the complexity to $0(N\ log\ N)$.

- It is an efficient algorithm, not a new kind of transform compared to DFT.

# Short-Term Fourier Transform (STFT)

- The Fourier Transform, DFT and FFT tell which frequencies exist in the signal, but not when they happen.

- The Short-Term Fourier Transform (STFT) adds this information by

  - Chopping the signal in short time windows (or frames).

  - Running FFT on each window.

## Uncertainty principle

### Definition

- The uncertainty principle is a trade-off with respect to the window size.

- Narrow windows offer a great time resolution because each window represents a precise location in time.

  - However, the frequency resolution is poor.

- Conversely, wide windows offer a great frequency resolution but a poor time resolution.

- The relation between the frequency and the time resolutions is $\Delta f \simeq \frac{1}{T}$ with

  - $\Delta f$ the frequency resolution in $Hz$.

  - $T$ the window length in $s$.

### Strategies

- Overlapping windows

  - Does not suppress the uncertainty principle.

  - But makes transitions between windows smoother.

  - Better catch events that occur on the edges of the windows if no overlap is used.

- Windows shapes
